### ISSUE TITLE
Remaining hundred bytes (waveform preview)

### ISSUE THREAD

**Issue by jan2000** [Deep-Symmetry/dysentery#17]
This looks like it is 100 pixels wide:
![image](https://user-images.githubusercontent.com/1422460/50872223-f2d0e080-13be-11e9-86f9-7a10fabcb996.png)

**Comment by brunchboy** [comment]
I’m afraid I don’t understand what this issue means?

**Comment by brunchboy** [comment]
Oh, are you saying that there are 100 bytes in the waveform preview that we did not previously know the purpose of, and this in-menu preview might be the purpose?

**Comment by jan2000** [comment]
Yes:
> I don’t yet know what the remaining hundred bytes mean; perhaps they are color information for players that support colored waveforms? More likely, however, color uses a different request and response pair, and we will have to wait for someone to take a packet capture of a nexus 2 player to see them.

**Comment by brunchboy** [comment]
Nice find! I will investigate further and update the analysis when I am back from traveling.
