### ISSUE TITLE
Document XDJ-XZ media slot quirks

### ISSUE THREAD

**Issue by brunchboy** [Deep-Symmetry/dysentery#49]
I just noticed that the protocol analysis document doesn’t mention the fact that the XDJ-XZ has to play tricks with the meaning of the media slot byte because it has only one IP address. In the relevant places, explain how the SD slot value must be used for the second USB slot on this hardware.

**Comment by xpdoc** [comment]
Indeed the XDJ-XZ has some tricks in place to handle the SD slot and is indeed true it holds a single ip address for the whole gear.
At the same time it also stays kinda consistent with other gear setup (DJM + 2x CDJ), so it advertises the two decks + mixer as 3 different devices with 3 different mac addresses.
Both the media slots on the XZ are on the first logic deck and can be used as if you were loading tracks either from the sd slot or the usb slot.

Hope this helps documenting

**Comment by brunchboy** [comment]
Thanks for the reminder to deal with this issue. We have implemented these details in Beat Link, and documented most of the other XZ variations in the protocol analysis, but never got around to adding a note about this. I’m doing that now. Are you certain that different MAC addresses are advertised? I can’t see any value in doing that, given that all network communication with these devices is done at the IP level, and the device numbers are sufficient to differentiate the player sections and mixer.
