### ISSUE TITLE
Create another window and implement it like CDJ3000 or RX3

### ISSUE THREAD

**Issue by GRDGRADI** [Deep-Symmetry/dysentery#51]
Hello, I am currently aiming to implement it like RX3 or CDJ3000 by adding a sub screen to DDJ 1000, and I got hope after seeing this project.  Using this project, I am planning to configure the UI used in the Pioneer all-in-one system, configure it in a new window, and then output it to a subscreen using a program such as OBS.  Is it possible to configure Rekordbox's UI like an all-in-one system UI by placing it in a new window?

**Comment by brunchboy** [comment]
I'm sorry but I can't understand the details of what you're proposing, but project issues are not the appropriate place for exploratory conversations, please create a topic in the [community chat](https://deep-symmetry.zulipchat.com/#narrow/stream/275855-dysentery-.26-crate-digger) instead. And when you do, can you be more precise and detailed about what you are trying to build, and for what hardware?
